
from PyQt5 import uic
import  tkinter as tk
from tkinter import filedialog
import os
import sys

root = tk.Tk()
root.withdraw()
ui_file = filedialog.askopenfilename(filetypes = [("UI files", ".ui")])
py_file = filedialog.askdirectory()
py_name = ui_file.split("/")[-1][:-2] + "py"
py_file = py_file + "/" + py_name

fp = open(py_file, "w")
uic.compileUi(ui_file, fp, from_imports = True)
fp.close()

# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
